// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://hgzqqxqvkshomuysdwfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnenFxeHF2a3Nob211eXNkd2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzE3OTQsImV4cCI6MjA2OTEwNzc5NH0.ajx8Zg9olsu7Py3fVhWHNnY_Aoa7jM8zBtQZmFNYGUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
